- name: Create jenkins user to deploy on webservers
  include_tasks: jenkins-user.yml
  delegate_to: $item
  with_items: "{{ groups.webservers }}"

- name: Check that the jenkins ssh key exists
  stat:
    path: /var/lib/jenkins/.ssh/id_rsa
  register: stat_result
  become: yes
  become_method: sudo

- name: Genrating ssh rsa key
  shell: ssh-keygen -b 2048 -t rsa -f /var/lib/jenkins/.ssh/id_rsa -q -N ""
  when: not stat_result.stat.exists
  become: yes
  become_method: sudo

- name: Genrating ssh rsa key
  shell: "{{ 'ssh-copy-id jenkins@' + $item }}"
  become: yes
  become_method: sudo
  with_items: ${groups.webservers}